Add support for bows
RappyLabyAddons/Toolbreak-Warning pull request #24
Opened 2024-07-23 11:04 UTC by Seeloewen

Fixes my issue opened in #23 
Accidentally added bows to migration from config v1, probably shouldn't matter though. If not, I can remove it.

2024-08-01 22:40 UTC, RappyTV requested changes
Hey 👋
Sorry for the late response, I just didn't receive a notification that you opened the pr ^^
Looks good so far! You'd still need to bump the version in the `build.gradle.kts` though :)

2024-08-01 22:40 UTC, RappyTV commented on core/src/main/java/com/rappytv/toolwarn/listener/ConfigMigrationListener.java
> +            bow = config.get("bowPercentage").getAsInt();
This needs to be removed as it would throw an exception resulting in every other value not being migrated
```suggestion
```

2024-08-01 22:57 UTC, Seeloewen commented
Removed the code for the migration. What is the version in build.gradle.kts used for? Just the project version? Sorry, I'm not often working with gradle or java in general.

2024-08-02 02:21 UTC, RappyTV commented
yea its the labymod addon version ^^

2024-08-02 02:23 UTC, RappyTV approved these changes
looks good. thanks for the pr :D

2024-08-02 02:29 UTC, merged

2024-08-02 02:34 UTC, RappyTV commented
it's released on [FlintMC](https://flintmc.net/modification/60.toolwarn) now. only thing left is waiting until nico approves it

2024-08-02 02:38 UTC, Seeloewen commented
Alright, great! Now is probably a good time to say thank you for this add-on, it really saved my tools a bunch of times :)

2024-08-02 06:08 UTC, RappyTV commented
thanks! it means a lot to me 😄